# Generated by Django 5.1.4 on 2025-01-02 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_ordersheet_order_order_sheet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordersheet',
            name='created_at',
        ),
    ]
