# Generated by Django 5.1.4 on 2025-01-02 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_ordersheet_created_at_ordersheet_sum_total_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_sheet',
        ),
    ]
