# Generated by Django 5.1.4 on 2025-01-02 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_order_order_sheet'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordersheet',
            name='orders',
            field=models.ManyToManyField(related_name='order_sheet', to='app.order'),
        ),
    ]
