# Generated by Django 5.1.4 on 2025-01-02 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_remove_order_product_remove_order_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='orders',
            field=models.ManyToManyField(blank=True, null=True, related_name='orders', to='app.orderitem'),
        ),
    ]
